#!/bin/sh

WHAT=$1
TIMEOUT=$2

if test -z ${WHAT}; then
	echo "$0 <process name>" && exit
fi

if test -z ${TIMEOUT}; then
	TIMEOUT=1
fi

while true; do
	ps xa -o vsz,rss,pcpu,pmem,nlwp,cmd \
	| grep -v pstat \
	| grep -v grep \
	| grep ${WHAT};
	sleep ${TIMEOUT};
done
